/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mht_signlib_ndksign */

#ifndef _Included_com_mht_signlib_ndksign
#define _Included_com_mht_signlib_ndksign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mht_signlib_ndksign
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mht_signlib_ndksign_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_mht_signlib_ndksign
 * Method:    getAppSignature
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mht_signlib_ndksign_getAppSignature
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mht_signlib_ndksign
 * Method:    getEncryptMD5ByAppSign
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mht_signlib_ndksign_getEncryptMD5ByAppSign
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_mht_signlib_ndksign
 * Method:    getEncryptMD5ToString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mht_signlib_ndksign_getEncryptMD5ToString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
